'use client';
import {useEffect,useMemo,useState} from 'react';
export default function Reader({doc}:{doc:any}){
 const [size,setSize]=useState(18),[contrast,setContrast]=useState(false),[spacing,setSpacing]=useState(false),[wide,setWide]=useState(false),[simple,setSimple]=useState(false),[speaking,setSpeaking]=useState(false);
 const sections=useMemo(()=>simple?doc.sections.map((s:any)=>({...s,content:s.content.map((x:string)=>x.replace(/\b(utilize|approximately|commence|subsequent)\b/gi,m=>({utilize:'use',approximately:'about',commence:'start',subsequent:'next'}[m.toLowerCase()]||m)))})):doc.sections,[simple,doc]);
 function speak(){if(typeof window==='undefined')return;if(speaking){speechSynthesis.cancel();setSpeaking(false);return}const text=sections.map((s:any)=>`${s.heading}. ${s.content.join('. ')}`).join('. ');const u=new SpeechSynthesisUtterance(text);u.onend=()=>setSpeaking(false);speechSynthesis.speak(u);setSpeaking(true)}
 useEffect(()=>()=>speechSynthesis?.cancel(),[]);
 return <div className={contrast?'contrast min-h-screen':''}><div className="mx-auto max-w-7xl p-5"><div className="flex flex-wrap gap-2 border-b border-white/10 pb-4 mb-6"><button onClick={()=>setSize(Math.max(14,size-2))}>A−</button><button onClick={()=>setSize(18)}>A</button><button onClick={()=>setSize(Math.min(28,size+2))}>A+</button><button onClick={()=>setContrast(!contrast)}>Contrast</button><button onClick={()=>setSpacing(!spacing)}>Spacing</button><button onClick={()=>setWide(!wide)}>Width</button><button onClick={()=>setSimple(!simple)}>{simple?'Normal':'Simplify'}</button><button onClick={speak}>{speaking?'Stop':'Read Aloud'}</button></div><main className="grid grid-cols-1 lg:grid-cols-[250px_1fr] gap-8"><aside className="hidden lg:block"><h2 className="font-bold mb-3">CONTENTS</h2>{doc.toc.map((x:any,i:number)=><div key={i} className="text-sm text-white/60 py-1">{'— '.repeat(Math.max(0,x.level-1))}{x.heading}</div>)}</aside><article className={`reader ${spacing?'spacing':''} ${wide?'wide':''} max-w-4xl`} style={{fontSize:size}}><p className="text-xs uppercase tracking-[.25em] text-red-400">ACCESSREAD</p><h1 className="text-4xl font-black mt-2 mb-8">{doc.title}</h1>{sections.map((s:any,i:number)=><section key={i} className="mb-8"><h2 className="text-2xl font-bold mb-3">{s.heading}</h2>{s.content.map((p:string,j:number)=><p key={j} className="mb-4">{p}</p>)}{s.items.length>0&&<ul className="list-disc pl-7">{s.items.map((x:string,j:number)=><li key={j}>{x}</li>)}</ul>}</section>)}</article></main></div></div>
}
